// Story is generated by AI, I changed the wording just a bit to help with flow
// but main story line is AI generated.

export const journal_entries = {
    1: {
        title: "Day 1: The Call to Adventure",
        text: "You awaken to the scent of aged parchment. The Journal lies blank before you. A voice echoes: 'To restore balance, master the simplest routines. Begin by tending to the vessel of the Hero: yourself.'",
    },
    2: {
        title: "Day 2: The First Forging",
        text: "The tasks of Day 1 are complete. You feel a subtle shift within. The voice returns: 'Chaos is vast, but small actions gather strength. Today, focus on consistency. It is the true currency of this realm.'",
    },
    3: {
        title: "Day 3: The Expanding Horizon",
        text: "Your resolve hardens. The fog on your mental map begins to clear. 'A Hero does not walk alone,' the Journal reads. 'Today, extend your spirit outward. Small kindnesses can ripple across the entire kingdom.'",
    },
    4: {
        title: "Day 4: The Clarity of Silence",
        text: "The noise of the world tries to drown out your purpose. 'To hear the path, you must first quiet the mind,' the Mentor whispers. 'Clear your surroundings and your thoughts will follow.'",
    },
    5: {
        title: "Day 5: The Architect's Blueprint",
        text: "You have reacted long enough. It is time to shape the future. The Journal pages are empty; your mentor commands, 'An action without a plan is but a dream. Map the day that follows and claim mastery over the coming dawn.'",
    },
    6: {
        title: "Day 6: The Creative Spark",
        text: "A Hero's strength is not just in battle, but in creation. The voice guides: 'Turn your attention to the inner fires. Tidy your world to clear the path for inspiration, and dedicate a few moments to the pure act of making.'",
    },
    7: {
        title: "Day 7: The Midpoint: Rest and Reflection",
        text: "The first week is complete. The Journal instructs: 'Look back at the roads you have traveled. Which paths brought you joy? Which led to distraction? Nourish your body and allow your mind to absorb the wisdom of your deeds.'",
    },
    8: {
        title: "Day 8: Reconnecting the Threads",
        text: "You step into the second week with newfound clarity. The Journal states: 'The strength of the realm lies in its bonds. Reach out to those who walk alongside you. Do not let your solitary quest sever the vital threads of community.'",
    },
    9: {
        title: "Day 9: The Sharpened Mind",
        text: "The Mentor urges deep focus: 'A cluttered mind yields cluttered work. Dedicate time to a singular, challenging task, and honor the world around you by leaving your environment better than you found it.'",
    },
    10: {
        title: "Day 10: Seeking Inner Stillness",
        text: "Physical actions ground you, but spiritual peace sustains you. 'Find the silent center of your being,' the Journal writes. 'Acquire a piece of knowledge today; understanding is the ultimate fortification.'",
    },
    11: {
        title: "Day 11: The Treasure Vault",
        text: "Your resources are finite, Hero. The Journal advises: 'Conduct an audit of your supplies. Reviewing your finances brings order to your future, ensuring you are prepared for unexpected turns in the road. Recharge your energy source with the light of the sun.'",
    },
    12: {
        title: "Day 12: Crafting a Legacy",
        text: "Near the end of your cycle, the voice asks: 'What is the skill you wish to master? Dedicate time to your craft. And finally, silence the digital din that steals your precious attention.'",
    },
    13: {
        title: "Day 13: Preparing the Ceremony",
        text: "The cycle nears its end. 'Tie up all loose ends,' the Journal commands. 'Prepare your mind and body for the final ceremony by allowing yourself restorative rest and reviewing the incredible distance you have travelled.'",
    },
    14: {
        title: "Day 14: The Hero's Triumph",
        text: "The voice is strong now: 'Your journey through this cycle is complete. Write your final thoughts and reflect on the person you were 14 days ago. Now, clear the clutter of the past and prepare the log for the next great adventure!'",
    },
};